export const DOOR_SCALE = 0.62;
export const DOOR_ANCHOR_CLOSED = {x : 1.41, y: 1.02};
export const DOOR_ANCHOR_OPENED = {x : 0.82, y: 1.018};
export const DOOR_ANCHOR_OPENED_SHADOW = {x : 0.74, y: 1.01};
export const HANDLE_SCALE = 0.4;
export const HANDLE_PIVOT = {x: 1.03, y: 1.85}
export const HANDLE_ANCHOR = {x : 0.5, y: 0.5};
export const HANDLE_ANCHOR_SHADOW = {x : 0.5, y: 0.5};
export const BLINK_SCALE = 0.3;
export const BLINK_ANCHOR = {x : 0.45, y: 0.36};
export const HANDLE_SHADOW_OFFSET = {x: 1.03, y: 1.95};
export const NUMBER_OF_PAIRS = 3;
export const TIME_TO_ENTER_PAIR = 50;
export const TIME_TO_RESTART_GAME = 300;
